### PR TITLE
Snip increment

### PR DESCRIPTION
**Pull request by rckirby**
Two minor changes:
1.) make the result of the form A0[j] = stuff rather than A0[j] = A0[j] + stuff
2.) Move tsfc_to_loopy down into tsfc as a module to make importing easier.

### CODE REVIEW

**Comment by inducer** [comment]
Can you take a look at the test failures? Also, you need to be updated up against the latest revision, otherwise this will not be mergeable.

**Comment by inducer** [comment]
There are also some remaining test failures in the base `loopy-output` branch:

https://github.com/firedrakeproject/tsfc/commit/6f3caa24fb3a3ebc217441f55e5d2e3a7ab21d7c

**Comment by rckirby** [comment]
I have no idea what this is about.  I didn't do those.

I also can't seem to pull up the pull request anymore.  Is it possible to
fully cancel the PR?

On Mon, Oct 31, 2016 at 10:32 AM, Andreas Klöckner <notifications@github.com

**Comment by miklos1** [comment]
@rckirby: you have already merged this PR.

**Pull request merged**
