### PR TITLE
FIAT and FInAT interface: add bindings for elements on hexahedra

### PR DESCRIPTION
**Pull request by wence-**
Resurrect some finished, but non-merged branches.

### CODE REVIEW

**Comment by miklos1** [comment]
Probably the reason I did not merge this, is that facet integrals were broken on unstructured hexahedra (only affects FEniCS since Firedrake only has semi-structured hexahedra). I described the issue in more detail in the future work section of my thesis.

**Comment by wence-** [comment]
Good point.  Probably I should add a `NotImplementedError` in `compile_form` if doing facet integrals + hexahedron in "spectral" mode.

**Comment by miklos1** [comment]
The problem occurs in other modes as well, because they originate from the tensor product element now being structured... and the conversion of elements UFL -> FInAT does not depend on mode.

**Comment by wence-** [comment]
Ah, OK, thanks.

**Pull request merged**
