### PR TITLE
Support averaging operators (fixes #107)

### LINKED ISSUE #107: Support for CellAvg and FacetAvg
Moving firedrakeproject/firedrake#1020 here, to make it easier to find TSFC related TODO items.

### PR DESCRIPTION
**Pull request by wence-**
Done by just integrating the averaged expression over the relevant
entity.

Needs a matching UFL merge.

### CODE REVIEW

**Comment by wence-** [comment]
That's here: https://bitbucket.org/fenics-project/ufl/pull-requests/89/cellavg-facetavg-are-no-longer-terminal/diff

**Comment by wence-** [comment]
This does the wrong thing for `cell_avg(inner(f, f))*dx` where f is VFS right now. I think I'm just being dense.

**Comment by wence-** [comment]
Think I fixed it, the XXX average is `(sum_q w_q expr_q) / (reference_entity_volume)`, not just `sum_q w_q expr_q`.

**Comment by blechta** [comment]
For affine transform cell, yes. For bendy cells each infinitesimal reference cell volume contributes differently to physical volume...

**Comment by wence-** [comment]
I don't think so.  Here's my reasoning.  For a function `f`, the mean over some compact domain U is `1/Vol(U) \int f dU`.  Which, with quadrature, is `(\sum_q w_q f_q) / (\sum_q w_q)`.

Now consider integrating `cell_avg(f)*dx`.

This is `\int_\Omega \bar{f} dx = \sum_e \int_e \bar{f} dx_e`.

Now I pull back to reference space:

`\sum_e \int_e \bar{f} dx_e = \sum_e \int_E \bar{\tilde{f}} \det J dX`

and `\bar{\tilde{f}} = \int_E \tilde{f} dX / Vol(dX)` (because we're already in reference space).

I think the only thing I assumed here was that averaging commutes will pullback.

Does this make sense?

**Comment by wence-** [comment]
This is still totally borked.  Promotes bugs in tsfc optimisation passes (possibly I'm doing something wrong).  Or doesn't work at all.

**Comment by blechta** [comment]
I don't think that the assumption is correct. We have

```
\bar{f} = \frac{ \int_e f dx }{ \int_e dx } = \frac{ \int_E \hat{f} |\det J| dX }{ \int_E |\det J| dX }
```

This is clearly not equal to

```
\frac{ \int_E \hat{f} dX }{ \int_E dX }
```

unless `\det J` is constant in `E`.

**Comment by wence-** [comment]
Thanks.  I've come to that conclusion too.  The latest commits do this "right", but still have issues elsewise.  So I'm holding off any merging for now.

**Comment by miklos1** [comment]
I like that you could implement this in such a small diff.

**Pull request merged**
