### PR TITLE
Attempt to do form splitting in TSFC for loo.py

### PR DESCRIPTION
**Pull request by miklos1**
Note that the target is `loopy-output`, not `master`.

This is quite a rude sketch to do form splitting and fused kernels inside TSFC. It doesn't work with Firedrake master since it changes the kernel API: due to fusion, kernels from mixed forms expect several arguments for return value (e.g. A0, A1, A2, A3 the four blocks of a mixed form).

@rckirby: please have a look and see if you can make use of this!

### CODE REVIEW

**Comment by rckirby** [comment]
So far I can confirm that this generates code that looks like what I expected for cell integrals on mixed spaces and that tsfc_to_loopy generates a loopy kernel without failure.  No attempt yet to process the loopy kernel.

**Comment by rckirby** [comment]
We now have a collection of output tensor "Ai" for i=0, 1, ...
Will these always correspond to the pieces of the test functions?
Or are there cases (e.g. cell integrals) where we might have len(test_space.split()) not equal to the number of output Ai's?

**Comment by wence-** [comment]
It will always, I think, be `len(test_space.split()) * len(trial_space.split())`

**Comment by miklos1** [comment]
@rckirby: I just pushed here a proposed fix for your recent issue.

**Comment by rckirby** [comment]
I've made the last changes I think this needs to provide for generating loopy code.  I think this can be merged back into loopy-output now.

**Pull request merged**
