### PR TITLE
Idempotency

### PR DESCRIPTION
**Pull request by wence-**
Make compile_form idempotent, and add a few tests thereof.  c.f. #12.

### CODE REVIEW

**Comment by miklos1** [comment]
Nice test, we don't actually need any data to compile a form, so no data is created.

**Comment by miklos1** [comment]
I see you're changing `Index.__repr__` and `Index.__slots__`.

**Comment by wence-** [comment]
One could avoid changing `Index` and instead do the following in `coffee.py`

```python
 def _index_name(index, parameters):
     if index.name.startswith("i_"):
         return parameters.index_names[index]
     return index.name
```

But this felt somewhat fragile.

**Comment by miklos1** [comment]
Ah, I see. OK, go ahead.

**Pull request merged**
