### PR TITLE
tests: drop python 3.8 and 3.9 and add 3.12 and 3.13

### PR DESCRIPTION
**Pull request by ksagiyam**

### CODE REVIEW

**Comment by connorjward** [comment]
Just to note. @JDBetteridge is currently in the process of migrating this entire repository into Firedrake. Ideally TSFC shouldn't really be accepting any PRs at the moment.

**Comment by ksagiyam** [comment]
I do not think he touches TSFC yet.

**Review by connorjward — APPROVED** [review]

**Comment by connorjward** [comment]
> I do not think he touches TSFC yet.

Yes you're quite right. Apologies.

**Comment by JDBetteridge** [comment]
Well I have, but it doesn't really matter.

This commit just won't be in there :shrug:

**Pull request merged**
